# Generated by Django 3.2.7 on 2021-10-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fechaVencimiento', models.DateField()),
                ('repetir', models.BooleanField()),
                ('descripcion', models.CharField(max_length=200)),
                ('prioridad', models.BooleanField()),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('repetir', models.BooleanField()),
                ('ubicacion', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.empresa')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lead')),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.agent')),
            ],
        ),
    ]
