# Generated by Django 3.2.7 on 2021-10-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211021_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.agent'),
        ),
    ]
