# Generated by Django 3.2.7 on 2021-10-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_lead_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.agent'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.agent'),
        ),
    ]
