# Generated by Django 3.2.7 on 2021-10-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211025_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('monto', models.FloatField()),
                ('fechaCierre', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lead')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.producto')),
            ],
        ),
    ]
