# Generated by Django 3.2.7 on 2021-10-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_deal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='fechaCierre',
            field=models.DateField(),
        ),
    ]
